### ISSUE TITLE
Step by step install guide

### ISSUE THREAD

**Issue by Jelle-S** [chunying/gaminganywhere#1]
As this is the first issue I simply have to say this first:
This is an absolutely amazing project. 

I haven't installed it yet (or even tried to) but I have read through the documentation and the quick start guide. I was wondering if it is possible to add a step-by-step installation guide because I find the current guide to be a bit vague at times. Even better would be an install script for (both server and client) Linux, Mac and Windows respectively. 

What I mean with "a bit vague" for example is:
>On Linux, you have to add 'deps.posix/lib' into system-wide ld.so search path. In addition, you have to modify 'bin/config/common/server-common.conf' and at least ensure that 'display' is set to an accessible X-Window desktop with XTEST extension enabled. The X-Window desktop can be a VNC or Xvfb desktop.

What is system-wilde ld.so, where do I find it, ...
Perhaps provide an example value for 'display' (I'm assuming it's an IP address and port?)

>The ga-server-periodic will stream the entire desktop to a client. If you plan to streaming only a (game) window, you can add the options:
1) find-window-name = [window name], or
2) find-window-class = [window class]
into the configuration file. The ga-server-periodic will attempt to find the specified window, move the window to top-left corner of the desktop, and capture only the client area of the specified window.

Where/how do I find the correct window name and class?

I think better documentation might help to get this project more accessible and known to the masses.

Again I want to stress that I think this is an absolutely amazing project and I hope to use it in the near future.

**Comment by bratanmol** [comment]
I think that for VNC the number is :1 for ubuntu or linux. Check this link.
https://www.linode.com/docs/applications/remote-desktop/using-vnc-to-operate-a-desktop-on-ubuntu-12-04
Also, i want to ask that  can we add the library path from .bashrc file?

**Comment by pourrahim** [comment]
hi
I have been struggling to install gaminganywhere on ubuntu 14.04. Here is the steps I go through in terminal, If needed I can give you the outputs too.
$ git clone https://github.com/chunying/gaminganywhere.git
$ cd gaminganywhere
$ sudo apt-get install gcc++ pkg-config libx11-dev libxext-dev libxtst-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libasound2 libasound2-dev // for this one I tried to do it separately. All of them get installed OK except gcc++, pkg-config and libasound2//
$ nano env-setup
$ source env-setup
$ cd deps.src
$ make // after running some codes gives error , the last line is " make: *** [theora] Error 2 "
$ cd ../ga
$ make all //gives error " make: *** [core] Error 2 " 
$ sudo make install // gives error as well


Sorry for long message. But I really need to install and run this. Can you please tell me which parts I am making mistakes. Thanks in advance

**Comment by cyb3rm4n** [comment]
try installing buildutiils

**Comment by sumu15** [comment]
hey,
Did you find any solution to your problem??
even i am also facing the same problem which u faced.......
please let me know......  @pourrahim
