### ISSUE TITLE
Conflicting types for ‘max_align_t’ (while building libvpx dep)

### ISSUE THREAD

**Issue by Blaxar** [chunying/gaminganywhere#12]
The title is self-explanatory:

```
In file included from test/../nestegg/halloc/src/halloc.c:19:0:
test/../nestegg/halloc/src/align.h:33:25: error: conflicting types for ‘max_align_t’
 typedef union max_align max_align_t;
                         ^
In file included from test/../nestegg/halloc/src/../halloc.h:18:0,
                 from test/../nestegg/halloc/src/halloc.c:18:
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include/stddef.h:429:3: note: previous declaration of ‘max_align_t’ was here
 } max_align_t;
```

This could be circumvented on my side by commenting/removing the corresponding line in halloc.h, but I guess it's here for a reason in the first place, still on some systems this may cause trouble as max_align_t is already defined in standard headers (with gcc 5.2.0 at least).

**Comment by Ghostbird** [comment]
I can confirm this issue on Debian Jessie. I circumvented it so far by installing libvpx-dev from the repository and removing vpx from the package list in Makefile. I will try and see whether it works that way.

**Comment by chunying** [comment]
We have upgraded vpx to 1.4, but I am not sure if this helps on this issue. You may have a test. BTW, we are also modifying an alternative version of dependency make file, which attempts to use system libraries instead of building all of them.

**Comment by mbrubeck** [comment]
I submitted kinetiknz/nestegg#31 which is a partial fix (works for GCC and Clang).
