### ISSUE TITLE
libvorbis does not build on armv7l

### ISSUE THREAD

**Issue by Ghostbird** [chunying/gaminganywhere#16]
cd libvorbis-1.3.4; ./configure --prefix=/home/osmc/myprog/gaminganywhere/deps.posix --build=armv7l --with-pic
    checking build system type... Invalid configuration `armv7l': machine `armv7l' not recognized

libvorbis and libvorbis-dev are already installed on my system (Raspbian)
I will remove it from the package list in the Makefile, and see whether it works with the system installed libvorbis.
It would be nice if the system detects this and does not try to build unnecessarily.

**Comment by Ghostbird** [comment]
GamingAnywhere builds successfully on armv7l using system installed libvorbis-dev (and it's dependency libvorbis0) from Raspbian Jessie repository. Tested on Raspberry Pi 2 running OSMC.

**Comment by chunying** [comment]
Actually we did not build all dependencies on Pi. You may refer to our Makefile.raspbian file (just committed), which only builds SDL2, SDL2_ttf, ffmpeg, and live555.
