### ISSUE TITLE
Phony dependencies make building unnecessarily difficult

### ISSUE THREAD

**Issue by Ghostbird** [chunying/gaminganywhere#17]
The current dependencies are implicitly phony, therefore they are always rebuilt. This is unnecessary and when a build fails, all dependencies are rebuilt, even those that were successfully built.

I suggest using make as (I think) it is intended to, and let the target specify a file that must be newer than the source files.

**Comment by chunying** [comment]
Working with a phony target is good. But we assume that only developers needs to do that (when debugging) and it only to be done once. Also you can specify the target name to build a single library instead of simply using 'make all' or 'make'.

**Comment by Ghostbird** [comment]
Actually this is probably a bit late, but my point was that currently everyone is working with a phony target, not just the developers. I am aware of the fact that it is possible to rebuild a single target, and I have used that.
