### ISSUE TITLE
audio video off sync (audio delay)

### ISSUE THREAD

**Issue by ntt1985** [chunying/gaminganywhere#18]
Hi, I have a problem of audio/video sync (precisely, audio has a delay of about 1 second). I'm using ubuntu 15.04 32bit with assaultcube. I tried with libmp3lame, libopus and pcm but nothing change. Please, can you give me some advises? The problem remains with new commit https://github.com/chunying/gaminganywhere/commit/cbf5c0f6e398756f60ca97aa4897e4b3454443bc

Thank you

**Comment by ntt1985** [comment]
After last commit https://github.com/chunying/gaminganywhere/commit/cf8aa39dad66a4646d76baf9e290315486fff648 I confirm that audio/video problem are solved. More precisely, I have best performance with opus and not with lame.
Little trick to identify available pulse audio devices:
pactl list | grep -A2 'Source #' | grep 'Name: ' | cut -d" " -f2

Thanks

**Comment by chunying** [comment]
Based on you reports, I think the audio capture with pulseaudio is much efficiency than alsa on certain platforms. On my testbed, the differences is almost negligible. Opus always claims that they have shorter delay. From my observations, mp3 starts encoding after collecting 1.5K frames, but Opus only needs 0.3K frames.
