### ISSUE TITLE
Gaming with EC2

### ISSUE THREAD

**Issue by moocow1452** [chunying/gaminganywhere#19]
If I wanted to try and hook my Android tablet to an Amazon Cloud computer, to get PC Games on aa portable device, would Gaming Anywhere be an ideal system? Or is the underlying hardware and latency not ready for primetime?

**Comment by Ghostbird** [comment]
I suggest you at least try to get it working (reliably) at home, then move it to EC2 for a test. I just did a small test, and I get latencies of more than 100ms to even the nearest EC2 centre, in Frankfurt. This may range from perfectly fine, for turn based games, to no problem, to totally unplayable for real-time first-person-<anything> games.
