### ISSUE TITLE
ga-hook-coreaudio.so LD_PRELOAD error (ubuntu - event driven)   

### ISSUE THREAD

**Issue by thorizer** [chunying/gaminganywhere#27]
When running an **sdl** game (assault cube or neverball) with the **event-driven** server on ubuntu **32** or **64** bit , I'm getting the same **preload** errors . 
I'm using the precompiled ga binaries.
The game starts and runs fine thought ! but the server isn't .

**A) on assault cube:**

> ERROR: ld.so: object '/home/user//home/user/Desktop/bin/ga-hook-sdl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**B) on neverball:**

> ERROR: ld.so: object '/home/user//home/user/Desktop/bin/ga-hook-sdl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

> ERROR: ld.so: object '/home/user//home/user/Desktop/bin/ga-hook-coreaudio.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Below I've uploaded two files for more detailed output.
[ac.txt](https://github.com/chunying/gaminganywhere/files/250171/ac.txt)
[neverball.txt](https://github.com/chunying/gaminganywhere/files/250172/neverball.txt)

Best regards.

**Comment by chunying** [comment]
I see duplicated /home/user/ ... It looks like the path is not correct!?

/home/user//home/user/Desktop/bin/ga-hook-sdl.so

**Comment by thorizer** [comment]
my bad, I was typing the absolute path.
Thanks a lot.

**Comment by thorizer** [comment]
it seems ga-hook-coreaudio is for windows only. I've commented the hook-audio in neberball config file but the game still hangs. 
Since it's just a config  problem not a ga bug , I'm closing this issue.
