### ISSUE TITLE
Compilation failed on raspberry pi 3

### ISSUE THREAD

**Issue by Fransiro** [chunying/gaminganywhere#35]
I follow the quickstart on: http://gaminganywhere.org/doc/quick_start.html
When i execute "make" on deps.src folder i get the follow error:
Makefile:37: recipe for target 'sdl2' failed.

And previous a get this error: 
/home/pi/gaminganywhere/deps.src/SDL2-2.0.3/src/render/software/SDL_blendpoint.c: In function ‘SDL_BlendPoint_RGB565’:
/home/pi/gaminganywhere/deps.src/SDL2-2.0.3/src/render/software/SDL_blendpoint.c:53:1: internal compiler error: Violación de segmento
 SDL_BlendPoint_RGB565(SDL_Surface * dst, int x, int y, SDL_BlendMode blendMode, Uint8 r,
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
Makefile:402: recipe for target 'build/SDL_blendpoint.lo' failed
make[1]: *** [build/SDL_blendpoint.lo] Error 1

This code is compatible with raspberry pi 3?

**Comment by miked63017** [comment]
FWIW I am able to build following the directions here http://gaminganywhere.org/doc/quick_start.html

I had a lot of libs already installed for other projects, but I think you should be able to:

```sudo apt-get install libX11-dev libXtst-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libasound2-dev```

I am running:
```pi@raspberrypi:~/streamer/gaminganywhere/bin $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~/streamer/gaminganywhere/bin $ uname -a
Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux```

On a Raspberry pi 3
