### ISSUE TITLE
Odd width and height?

### ISSUE THREAD

**Issue by SMUsamaShah** [chunying/gaminganywhere#37]
This line makes it sure that width and height are odd . 
https://github.com/chunying/gaminganywhere/blob/master/ga/core/ga-common.cpp#L788

Shouldn't it be doing the exact opposite? Width and height should be in EVEN not ODD.

**Comment by chunying** [comment]
This line is correct. Width (and height) should be in EVEN, so when modulo 2 is not zero, we increase the width by 1.

**Comment by SMUsamaShah** [comment]
Sorry, I discussed it and found that correct way to calculate width or height is (right - left + 1). +1 is necessary.
