### ISSUE TITLE
Getting Error after 'make all' in ga directory :- /usr/bin/ld: warning: libx265.so.79, needed by /home/asimniazi63/myprog/gaminganywhere/deps.posix/lib/libavcodec.so, not found (try using -rpath or -rpath-link)

### ISSUE THREAD

**Issue by asimniazi63** [chunying/gaminganywhere#48]
here is the terminal output:-

make[2]: Entering directory `/home/asimniazi63/Desktop/gaminganywhere/ga/server/periodic'
g++ -o ga-server-periodic ga-server-periodic.o  -L/home/asimniazi63/myprog/gaminganywhere/deps.posix/lib -Wl,-rpath,\$ORIGIN -lpthread -rdynamic -L../../core -lga -L/home/asimniazi63/myprog/gaminganywhere/deps.posix/lib -lswscale -lswresample -lpostproc -lavdevice -lavfilter -lavcodec -lavformat -lavutil   -lSDL2_ttf -lSDL2    -lasound -lX11 -lXext -lXtst
/usr/bin/ld: warning: libx265.so.79, needed by /home/asimniazi63/myprog/gaminganywhere/deps.posix/lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/home/asimniazi63/myprog/gaminganywhere/deps.posix/lib/libavcodec.so: undefined reference to `x265_api_get_79'
collect2: error: ld returned 1 exit status
make[2]: *** [ga-server-periodic] Error 1
make[2]: Leaving directory `/home/asimniazi63/Desktop/gaminganywhere/ga/server/periodic'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/home/asimniazi63/Desktop/gaminganywhere/ga/server'
make: *** [server] Error 2

**Comment by asimniazi63** [comment]
Actually needed to add .conf file containing the path to deps.posix in /etc/ld.so.conf.d

**Comment by q437634645** [comment]
Hi.
I have the same problem.Have you solved this problem?

**Comment by sab-sv** [comment]
@asimniazi63  What should be the name of the .conf file?
