### ISSUE TITLE
"ntwin32.mak file not found" error when attempting to build

### ISSUE THREAD

**Issue by jmzg1229** [chunying/gaminganywhere#6]
Using the quickstart guide on the official website I've been stuck on step 4 that says:
"Build GA by running 'nmake /f NMakefile all' command in the 'ga' directory."
It gives me the error mentioned above. I installed microsoft sdk and VS 2010 C++ redistributable (from the same installer) successfully, acquired a ntwin32.mak file from the internet and pasted it into the only include folder withing the entire project and still it doesnt work, can anyone help? My system is 64 bit just in case.

Microsoft (R) Program Maintenance Utility Version 11.00.61030.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cd core && nmake /f NMakefile && cd ..

Microsoft (R) Program Maintenance Utility Version 11.00.61030.0
Copyright (C) Microsoft Corporation.  All rights reserved.

..\NMakefile.def(10) : fatal error U1052: file 'ntwin32.mak' not found
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

**Comment by wxj2829232101** [comment]
@jmzg1229   Hi,I got a same problem (fatal error U1052: file 'ntwin32.mak' not found), I found resolutions everywhere but it still doesn't work.
How did you figure it out?

**Comment by chunying** [comment]
Are you working with visual studio 2013? GA has to work with visual studio
2010.

Chun-Ying

**Comment by wxj2829232101** [comment]
Thank you!  
I was working with visual studio 2015. Now I change to work with visual studio 2010, and the problem is gone.
