### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ghost** [chunying/gaminganywhere#88]
Hope you will take him up )

**Comment by keichi** [comment]
In the meantime, we can use https://web.archive.org/web/20200218041709/http://gaminganywhere.org/

**Comment by chintan-mishra** [comment]
It is back online. You can close this issue

**Comment by keichi** [comment]
Is it down again?

<img alt="Screen Shot 2020-11-09 at 20 44 11" src="https://user-images.githubusercontent.com/791283/98537375-8251be00-22cc-11eb-9542-ba5ecc0bf86f.png">

**Comment by chintan-mishra** [comment]
Hey @keichi not for me. I am using the website. Refresh the webpage and clear the cache.
Ctrl+F5 does the trick

**Comment by keichi** [comment]
Thanks @chintan-mishra, I can access it now. I thought I refreshed the cash but maybe I didn't.
